parameters:
    lia.factory.database.pdo.class: Lia\Database\PdoBundle\DependencyInjection\Factory

services:
    lia.factory.database.pdo:
        class: %lia.factory.database.pdo.class%
        calls:
            - ['setContainer', [@service_container]]